CC = g++

CFLAGS = -O3 -Wall -Werror -Wextra -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wlogical-op -Wreturn-type -fwhole-program

all: Fraction_main

Fraction_main:
	$(CC) $(CFLAGS) Fraction_main.cpp -o Fraction_main.exe